# Venture Funding with Deep Learning

You work as a risk management associate at Alphabet Soup, a venture capital firm. Alphabet Soup’s business team receives many funding applications from startups every day. This team has asked you to help them create a model that predicts whether applicants will be successful if funded by Alphabet Soup.

The business team has given you a CSV containing more than 34,000 organizations that have received funding from Alphabet Soup over the years. With your knowledge of machine learning and neural networks, you decide to use the features in the provided dataset to create a binary classifier model that will predict whether an applicant will become a successful business. The CSV file contains a variety of information about these businesses, including whether or not they ultimately became successful.

## Instructions:

The steps for this challenge are broken out into the following sections:

* Prepare the data for use on a neural network model.

* Compile and evaluate a binary classification model using a neural network.

* Optimize the neural network model.

### Prepare the Data for Use on a Neural Network Model 

Using your knowledge of Pandas and scikit-learn’s `StandardScaler()`, preprocess the dataset so that you can use it to compile and evaluate the neural network model later.

Open the starter code file, and complete the following data preparation steps:

1. Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.   

2. Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.
 
3. Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

4. Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course. 

5. Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset. 

6. Split the features and target sets into training and testing datasets.

7. Use scikit-learn's `StandardScaler` to scale the features data.

### Compile and Evaluate a Binary Classification Model Using a Neural Network

Use your knowledge of TensorFlow to design a binary classification deep neural network model. This model should use the dataset’s features to predict whether an Alphabet Soup&ndash;funded startup will be successful based on the features in the dataset. Consider the number of inputs before determining the number of layers that your model will contain or the number of neurons on each layer. Then, compile and fit your model. Finally, evaluate your binary classification model to calculate the model’s loss and accuracy. 
 
To do so, complete the following steps:

1. Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

2. Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

> **Hint** When fitting the model, start with a small number of epochs, such as 20, 50, or 100.

3. Evaluate the model using the test data to determine the model’s loss and accuracy.

4. Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`. 

### Optimize the Neural Network Model

Using your knowledge of TensorFlow and Keras, optimize your model to improve the model's accuracy. Even if you do not successfully achieve a better accuracy, you'll need to demonstrate at least two attempts to optimize the model. You can include these attempts in your existing notebook. Or, you can make copies of the starter notebook in the same folder, rename them, and code each model optimization in a new notebook. 

> **Note** You will not lose points if your model does not achieve a high accuracy, as long as you make at least two attempts to optimize the model.

To do so, complete the following steps:

1. Define at least three new deep neural network models (the original plus 2 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

2. After finishing your models, display the accuracy scores achieved by each model, and compare the results.

3. Save each of your models as an HDF5 file.

In [2]:
# Imports
import pandas as pd
from pathlib import Path
import tensorflow as tf
from tensorflow.keras.layers import Dense
from tensorflow.keras.models import Sequential
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler,OneHotEncoder

C:\Users\Russell\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:516: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Russell\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:517: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Russell\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:518: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Russell\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:519: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Russell\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:520: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Russell\Anaconda3\lib\site-packages\tensorflow\python\framework\dtypes.py:525: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])
C:\Users\Russell\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:541: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint8 = np.dtype([("qint8", np.int8, 1)])
C:\Users\Russell\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:542: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint8 = np.dtype([("quint8", np.uint8, 1)])
C:\Users\Russell\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:543: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint16 = np.dtype([("qint16", np.int16, 1)])
C:\Users\Russell\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:544: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_quint16 = np.dtype([("quint16", np.uint16, 1)])
C:\Users\Russell\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:545: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  _np_qint32 = np.dtype([("qint32", np.int32, 1)])
C:\Users\Russell\Anaconda3\lib\site-packages\tensorboard\compat\tensorflow_stub\dtypes.py:550: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  np_resource = np.dtype([("resource", np.ubyte, 1)])

---

## Prepare the data to be used on a neural network model

### Step 1: Read the `applicants_data.csv` file into a Pandas DataFrame. Review the DataFrame, looking for categorical variables that will need to be encoded, as well as columns that could eventually define your features and target variables.

In [3]:
# Read the applicants_data.csv file from the Resources folder into a Pandas DataFrame
applicant_data_df = pd.read_csv(
    Path("Resources/applicants_data.csv"))


# Review the DataFrame
applicant_data_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [4]:
# Review the data types associated with the columns
applicant_data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 34299 entries, 0 to 34298
Data columns (total 12 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   EIN                     34299 non-null  int64
 1   NAME                    34299 non-null  object
 2   APPLICATION_TYPE        34299 non-null  object
 3   AFFILIATION             34299 non-null  object
 4   CLASSIFICATION          34299 non-null  object
 5   USE_CASE                34299 non-null  object
 6   ORGANIZATION            34299 non-null  object
 7   STATUS                  34299 non-null  int64
 8   INCOME_AMT              34299 non-null  object
 9   SPECIAL_CONSIDERATIONS  34299 non-null  object
 10  ASK_AMT                 34299 non-null  int64
 11  IS_SUCCESSFUL           34299 non-null  int64
dtypes: int64(4), object(8)
memory usage: 3.1+ MB

### Step 2: Drop the “EIN” (Employer Identification Number) and “NAME” columns from the DataFrame, because they are not relevant to the binary classification model.

In [5]:
# Drop the 'EIN' and 'NAME' columns from the DataFrame
applicant_data_df = applicant_data_df.drop(["EIN", "NAME"], axis=1)

# Review the DataFrame
applicant_data_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

### Step 3: Encode the dataset’s categorical variables using `OneHotEncoder`, and then place the encoded variables into a new DataFrame.

In [6]:
# Create a list of categorical variables 
categorical_variables = list(applicant_data_df.dtypes[applicant_data_df.dtypes == "object"].index)

# Display the categorical variables list
categorical_variables

['APPLICATION_TYPE',
 'AFFILIATION',
 'CLASSIFICATION',
 'USE_CASE',
 'ORGANIZATION',
 'INCOME_AMT',
 'SPECIAL_CONSIDERATIONS']

In [7]:
# Create a OneHotEncoder instance
enc = OneHotEncoder(sparse=False)

In [8]:
# Encode the categorcal variables using OneHotEncoder
encoded_data = enc.fit_transform(applicant_data_df[categorical_variables])

In [9]:
# Create a DataFrame with the encoded variables
encoded_df = encoded_df = pd.DataFrame(
    encoded_data,
    columns = enc.get_feature_names(categorical_variables)
)

# Review the DataFrame
encoded_df.head()

,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,APPLICATION_TYPE_T25,APPLICATION_TYPE_T29,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 4: Add the original DataFrame’s numerical variables to the DataFrame containing the encoded variables.

> **Note** To complete this step, you will employ the Pandas `concat()` function that was introduced earlier in this course.

In [10]:
# Add the numerical variables from the original DataFrame to the one-hot encoding DataFrame
numerical_variables_df = applicant_data_df.drop(columns = categorical_variables)
encoded_df = pd.concat(
    [
        numerical_variables_df,
        encoded_df
    ],
    axis=1
)

# Review the Dataframe
encoded_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,1.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,1,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 5: Using the preprocessed data, create the features (`X`) and target (`y`) datasets. The target dataset should be defined by the preprocessed DataFrame column “IS_SUCCESSFUL”. The remaining columns should define the features dataset.

In [11]:
# Define the target set y using the IS_SUCCESSFUL column
y = encoded_df["IS_SUCCESSFUL"]

# Display a sample of y
y[:5]

0    1
1    1
2    0
3    1
4    1
Name: IS_SUCCESSFUL, dtype: int64

In [12]:
# Define features set X by selecting all columns but IS_SUCCESSFUL
X = encoded_df.drop(columns=["IS_SUCCESSFUL"])

# Review the features DataFrame
X.head()

,STATUS,ASK_AMT,APPLICATION_TYPE_T10,APPLICATION_TYPE_T12,APPLICATION_TYPE_T13,APPLICATION_TYPE_T14,APPLICATION_TYPE_T15,APPLICATION_TYPE_T17,APPLICATION_TYPE_T19,APPLICATION_TYPE_T2,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
1,1,108590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
2,1,5000,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
3,1,6692,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
4,1,142590,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0

### Step 6: Split the features and target sets into training and testing datasets.

In [13]:
# Split the preprocessed data into a training and testing dataset
# Assign the function a random_state equal to 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=1)

### Step 7: Use scikit-learn's `StandardScaler` to scale the features data.

In [14]:
# Create a StandardScaler instance
scaler = StandardScaler()

# Fit the scaler to the features training dataset
X_scaler = scaler.fit(X_train)

# Fit the scaler to the features training dataset
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

---

## Compile and Evaluate a Binary Classification Model Using a Neural Network

### Step 1: Create a deep neural network by assigning the number of input features, the number of layers, and the number of neurons on each layer using Tensorflow’s Keras.

> **Hint** You can start with a two-layer deep neural network model that uses the `relu` activation function for both layers.

In [16]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons = 1

In [17]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1 =  (number_input_features + 1) // 2

# Review the number hidden nodes in the first layer
hidden_nodes_layer1

58

In [18]:
# Define the number of hidden nodes for the second hidden layer
hidden_nodes_layer2 =  (hidden_nodes_layer1 + 1) // 2

# Review the number hidden nodes in the second layer
hidden_nodes_layer2

29

In [19]:
# Create the Sequential model instance
nn = Sequential()

In [20]:
# Add the first hidden layer
nn.add(Dense(units=hidden_nodes_layer1, input_dim=number_input_features, activation="relu"))

WARNING:tensorflow:From C:\Users\Russell\Anaconda3\lib\site-packages\tensorflow\python\ops\init_ops.py:1251: calling VarianceScaling.__init__ (from tensorflow.python.ops.init_ops) with dtype is deprecated and will be removed in a future version.
Instructions for updating:
Call initializer instance with the dtype argument instead of passing it to the constructor

In [21]:
# Add the second hidden layer
nn.add(Dense(units=hidden_nodes_layer2, activation="relu"))

In [22]:
# Add the output layer to the model specifying the number of output neurons and activation function
nn.add(Dense(units=1, activation="sigmoid"))

In [23]:
# Display the Sequential model summary
nn.summary()

Model: "sequential"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense (Dense)                (None, 58)                6786
_________________________________________________________________
dense_1 (Dense)              (None, 29)                1711
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 30
=================================================================
Total params: 8,527
Trainable params: 8,527
Non-trainable params: 0
_________________________________________________________________

### Step 2: Compile and fit the model using the `binary_crossentropy` loss function, the `adam` optimizer, and the `accuracy` evaluation metric.

In [24]:
# Compile the Sequential model
nn.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

WARNING:tensorflow:From C:\Users\Russell\Anaconda3\lib\site-packages\tensorflow\python\ops\nn_impl.py:180: add_dispatch_support.<locals>.wrapper (from tensorflow.python.ops.array_ops) is deprecated and will be removed in a future version.
Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

In [25]:
# Fit the model using 50 epochs and the training data
fit_model = nn.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
25724/25724 [==============================] - 2s 83us/sample - loss: 0.5760 - acc: 0.7207
Epoch 2/50
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5538 - acc: 0.7297
Epoch 3/50
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5496 - acc: 0.7313
Epoch 4/50
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5476 - acc: 0.73260s - loss: 0.5472 - acc:
Epoch 5/50
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5460 - acc: 0.7325
Epoch 6/50
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5452 - acc: 0.7338
Epoch 7/50
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5436 - acc: 0.7339
Epoch 8/50
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5436 - acc: 0.7343
Epoch 9/50
25724/25724 [==============================] - 2s 71us/sample - loss: 0.5423 - acc: 0.7355
Epoch 10/50
25724/25724 [==============================] - 2s 60us/sample - loss: 0.5418 - acc: 0.7343
Epoch 11/50
25724/25724 [==============================] - 2s 59us/sample - loss: 0.5413 - acc: 0.7355
Epoch 12/50
25724/25724 [==============================] - 1s 58us/sample - loss: 0.5411 - acc: 0.7359
Epoch 13/50
25724/25724 [==============================] - 2s 67us/sample - loss: 0.5407 - acc: 0.7348
Epoch 14/50
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5402 - acc: 0.7377
Epoch 15/50
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5389 - acc: 0.7358
Epoch 16/50
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5386 - acc: 0.7372
Epoch 17/50
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5384 - acc: 0.7373
Epoch 18/50
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5385 - acc: 0.7369
Epoch 19/50
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5381 - acc: 0.7373
Epoch 20/50
25724/25724 [==============================] - 1s 56us/sample - loss: 0.5376 - acc: 0.7378
Epoch 21/50
25724/25724 [==============================] - 2s 65us/sample - loss: 0.5374 - acc: 0.7380
Epoch 22/50
25724/25724 [==============================] - 2s 65us/sample - loss: 0.5375 - acc: 0.7379
Epoch 23/50
25724/25724 [==============================] - 2s 73us/sample - loss: 0.5366 - acc: 0.7384
Epoch 24/50
25724/25724 [==============================] - 2s 65us/sample - loss: 0.5369 - acc: 0.7386
Epoch 25/50
25724/25724 [==============================] - 2s 58us/sample - loss: 0.5364 - acc: 0.7383
Epoch 26/50
25724/25724 [==============================] - 1s 54us/sample - loss: 0.5365 - acc: 0.73940s - loss: 0.5402
Epoch 27/50
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5358 - acc: 0.7386
Epoch 28/50
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5357 - acc: 0.7391
Epoch 29/50
25724/25724 [==============================] - 2s 67us/sample - loss: 0.5352 - acc: 0.7387
Epoch 30/50
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5352 - acc: 0.7391
Epoch 31/50
25724/25724 [==============================] - 2s 61us/sample - loss: 0.5348 - acc: 0.7390
Epoch 32/50
25724/25724 [==============================] - 2s 59us/sample - loss: 0.5350 - acc: 0.73930s - loss: 0.5
Epoch 33/50
25724/25724 [==============================] - 2s 60us/sample - loss: 0.5347 - acc: 0.7402
Epoch 34/50
25724/25724 [==============================] - 2s 59us/sample - loss: 0.5344 - acc: 0.74010s - loss: 0.5325 - ac
Epoch 35/50
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5344 - acc: 0.7399
Epoch 36/50
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5342 - acc: 0.7399
Epoch 37/50
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5340 - acc: 0.73941s - l
Epoch 38/50
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5339 - acc: 0.74000s - loss: 0.5323 - ac
Epoch 39/50
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5337 - acc: 0.7400
Epoch 40/50
25724/25724 [==============================] - 2s 66us/sample - loss: 0.5333 - acc: 0.7405
Epoch 41/50
25724/25724 [==============================] - 2s 67us/sample - loss: 0.5334 - acc: 0.7409
Epoch 42/50
25724/25724 [==============================] - 1s 58us/sample - loss: 0.5336 - acc: 0.7407
Epoch 43/50
25724/25724 [==============================] - 2s 60us/sample - loss: 0.5334 - acc: 0.7402
Epoch 44/50
25724/25724 [==============================] - 2s 61us/sample - loss: 0.5329 - acc: 0.7401
Epoch 45/50
25724/25724 [==============================] - 2s 65us/sample - loss: 0.5328 - acc: 0.7404
Epoch 46/50
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5327 - acc: 0.7405
Epoch 47/50
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5324 - acc: 0.7412
Epoch 48/50
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5322 - acc: 0.7412
Epoch 49/50
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5323 - acc: 0.7411
Epoch 50/50
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5321 - acc: 0.7404

### Step 3: Evaluate the model using the test data to determine the model’s loss and accuracy.

In [26]:
# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

8575/8575 - 0s - loss: 0.5553 - acc: 0.7300
Loss: 0.5553375081070658, Accuracy: 0.7300291657447815

### Step 4: Save and export your model to an HDF5 file, and name the file `AlphabetSoup.h5`.

In [33]:
# Export your model to a HDF5 file
nn.save("AlphabetSoup.h5")

---

## Optimize the neural network model

### Step 1: Define at least three new deep neural network models (resulting in the original plus 3 optimization attempts). With each, try to improve on your first model’s predictive accuracy.

> **Rewind** Recall that perfect accuracy has a value of 1, so accuracy improves as its value moves closer to 1. To optimize your model for a predictive accuracy as close to 1 as possible, you can use any or all of the following techniques:
>
> * Adjust the input data by dropping different features columns to ensure that no variables or outliers confuse the model.
>
> * Add more neurons (nodes) to a hidden layer.
>
> * Add more hidden layers.
>
> * Use different activation functions for the hidden layers.
>
> * Add to or reduce the number of epochs in the training regimen.

### Alternative Model 1

In [34]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [35]:
# Define the number of neurons in the output layer
number_output_neurons_A1 = 1

In [37]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A1 =  77

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A1

77

In [38]:
# Create the Sequential model instance
nn_A1 = Sequential()

In [39]:
# First hidden layer
nn_A1.add(Dense(units=hidden_nodes_layer1_A1, input_dim=number_input_features, activation="relu"))


# Output layer
nn_A1.add(Dense(units=1, activation="sigmoid"))


# Check the structure of the model
nn_A1.summary()

Model: "sequential_1"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_3 (Dense)              (None, 77)                9009
_________________________________________________________________
dense_4 (Dense)              (None, 1)                 78
=================================================================
Total params: 9,087
Trainable params: 9,087
Non-trainable params: 0
_________________________________________________________________

In [40]:
# Compile the Sequential model
nn_A1.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [41]:
# Fit the model using 50 epochs and the training data
fit_model_A1 = nn_A1.fit(X_train_scaled, y_train, epochs=50)

Epoch 1/50
25724/25724 [==============================] - 2s 67us/sample - loss: 0.5809 - acc: 0.7186
Epoch 2/50
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5587 - acc: 0.7282
Epoch 3/50
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5535 - acc: 0.7295
Epoch 4/50
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5515 - acc: 0.7296
Epoch 5/50
25724/25724 [==============================] - 1s 47us/sample - loss: 0.5503 - acc: 0.7310
Epoch 6/50
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5487 - acc: 0.7310
Epoch 7/50
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5485 - acc: 0.7314
Epoch 8/50
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5474 - acc: 0.7319
Epoch 9/50
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5464 - acc: 0.7332
Epoch 10/50
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5463 - acc: 0.7317
Epoch 11/50
25724/25724 [==============================] - 1s 54us/sample - loss: 0.5461 - acc: 0.7325
Epoch 12/50
25724/25724 [==============================] - 1s 58us/sample - loss: 0.5452 - acc: 0.7322
Epoch 13/50
25724/25724 [==============================] - 1s 57us/sample - loss: 0.5450 - acc: 0.7351
Epoch 14/50
25724/25724 [==============================] - 1s 57us/sample - loss: 0.5439 - acc: 0.7338
Epoch 15/50
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5433 - acc: 0.7346
Epoch 16/50
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5439 - acc: 0.7349
Epoch 17/50
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5433 - acc: 0.7346
Epoch 18/50
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5426 - acc: 0.7350
Epoch 19/50
25724/25724 [==============================] - 2s 66us/sample - loss: 0.5426 - acc: 0.7349
Epoch 20/50
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5423 - acc: 0.7347
Epoch 21/50
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5424 - acc: 0.7346
Epoch 22/50
25724/25724 [==============================] - 1s 55us/sample - loss: 0.5420 - acc: 0.7346
Epoch 23/50
25724/25724 [==============================] - 2s 65us/sample - loss: 0.5418 - acc: 0.7350
Epoch 24/50
25724/25724 [==============================] - 2s 65us/sample - loss: 0.5412 - acc: 0.7352
Epoch 25/50
25724/25724 [==============================] - 2s 74us/sample - loss: 0.5417 - acc: 0.7356
Epoch 26/50
25724/25724 [==============================] - 2s 61us/sample - loss: 0.5408 - acc: 0.7358
Epoch 27/50
25724/25724 [==============================] - 2s 61us/sample - loss: 0.5405 - acc: 0.7351
Epoch 28/50
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5410 - acc: 0.7363
Epoch 29/50
25724/25724 [==============================] - 2s 95us/sample - loss: 0.5406 - acc: 0.73511 - ETA: 0s - loss: 0.5411 - acc: 0.
Epoch 30/50
25724/25724 [==============================] - 2s 80us/sample - loss: 0.5404 - acc: 0.7355
Epoch 31/50
25724/25724 [==============================] - 2s 73us/sample - loss: 0.5404 - acc: 0.7356
Epoch 32/50
25724/25724 [==============================] - 3s 113us/sample - loss: 0.5399 - acc: 0.7363
Epoch 33/50
25724/25724 [==============================] - 2s 65us/sample - loss: 0.5407 - acc: 0.7361
Epoch 34/50
25724/25724 [==============================] - 2s 61us/sample - loss: 0.5401 - acc: 0.7352
Epoch 35/50
25724/25724 [==============================] - 2s 63us/sample - loss: 0.5398 - acc: 0.7354
Epoch 36/50
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5411 - acc: 0.7362
Epoch 37/50
25724/25724 [==============================] - 1s 55us/sample - loss: 0.5396 - acc: 0.7362
Epoch 38/50
25724/25724 [==============================] - 2s 60us/sample - loss: 0.5392 - acc: 0.7355
Epoch 39/50
25724/25724 [==============================] - 1s 56us/sample - loss: 0.5390 - acc: 0.7369
Epoch 40/50
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5390 - acc: 0.7368
Epoch 41/50
25724/25724 [==============================] - 1s 54us/sample - loss: 0.5386 - acc: 0.7367
Epoch 42/50
25724/25724 [==============================] - 2s 81us/sample - loss: 0.5389 - acc: 0.7372
Epoch 43/50
25724/25724 [==============================] - 2s 76us/sample - loss: 0.5388 - acc: 0.73641s - l
Epoch 44/50
25724/25724 [==============================] - 2s 63us/sample - loss: 0.5385 - acc: 0.7354
Epoch 45/50
25724/25724 [==============================] - 2s 62us/sample - loss: 0.5384 - acc: 0.7378
Epoch 46/50
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5384 - acc: 0.7369
Epoch 47/50
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5388 - acc: 0.7378
Epoch 48/50
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5380 - acc: 0.7376
Epoch 49/50
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5377 - acc: 0.7379
Epoch 50/50
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5374 - acc: 0.7371

#### Alternative Model 2

In [42]:
# Define the the number of inputs (features) to the model
number_input_features = len(X_train.iloc[0])

# Review the number of features
number_input_features

116

In [ ]:
# Define the number of neurons in the output layer
number_output_neurons_A2 = 1

In [43]:
# Define the number of hidden nodes for the first hidden layer
hidden_nodes_layer1_A2 = 80

# Review the number of hidden nodes in the first layer
hidden_nodes_layer1_A2

80

In [44]:
# Create the Sequential model instance
nn_A2 = Sequential()

In [45]:
# First hidden layer
nn_A2.add(Dense(units=hidden_nodes_layer1_A2, input_dim=number_input_features, activation="relu"))

# Output layer
nn_A2.add(Dense(units=1, activation="sigmoid"))

# Check the structure of the model
nn_A2.summary()

Model: "sequential_2"
_________________________________________________________________
Layer (type)                 Output Shape              Param #
=================================================================
dense_5 (Dense)              (None, 80)                9360
_________________________________________________________________
dense_6 (Dense)              (None, 1)                 81
=================================================================
Total params: 9,441
Trainable params: 9,441
Non-trainable params: 0
_________________________________________________________________

In [47]:
# Compile the model
nn_A2.compile(loss="binary_crossentropy", optimizer="adam", metrics=["accuracy"])

In [48]:
# Fit the model
fit_model_A2 = nn_A2.fit(X_train_scaled, y_train, epochs=100)

Epoch 1/100
25724/25724 [==============================] - 1s 57us/sample - loss: 0.5874 - acc: 0.7169
Epoch 2/100
25724/25724 [==============================] - 2s 63us/sample - loss: 0.5588 - acc: 0.7280
Epoch 3/100
25724/25724 [==============================] - 2s 59us/sample - loss: 0.5550 - acc: 0.7287
Epoch 4/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5527 - acc: 0.7283
Epoch 5/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5509 - acc: 0.7327
Epoch 6/100
25724/25724 [==============================] - 2s 70us/sample - loss: 0.5492 - acc: 0.7321
Epoch 7/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5481 - acc: 0.7306
Epoch 8/100
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5484 - acc: 0.7323
Epoch 9/100
25724/25724 [==============================] - 2s 59us/sample - loss: 0.5468 - acc: 0.73160s - loss: 0.5464 - acc: 0.
Epoch 10/100
25724/25724 [==============================] - 2s 59us/sample - loss: 0.5472 - acc: 0.7323
Epoch 11/100
25724/25724 [==============================] - 1s 57us/sample - loss: 0.5463 - acc: 0.7327
Epoch 12/100
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5457 - acc: 0.7333
Epoch 13/100
25724/25724 [==============================] - 1s 54us/sample - loss: 0.5455 - acc: 0.7335
Epoch 14/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5452 - acc: 0.7328
Epoch 15/100
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5442 - acc: 0.7339
Epoch 16/100
25724/25724 [==============================] - 1s 54us/sample - loss: 0.5436 - acc: 0.7337
Epoch 17/100
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5437 - acc: 0.7332
Epoch 18/100
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5438 - acc: 0.7340
Epoch 19/100
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5436 - acc: 0.7336
Epoch 20/100
25724/25724 [==============================] - 2s 63us/sample - loss: 0.5426 - acc: 0.7334
Epoch 21/100
25724/25724 [==============================] - 2s 63us/sample - loss: 0.5428 - acc: 0.7340
Epoch 22/100
25724/25724 [==============================] - 2s 58us/sample - loss: 0.5428 - acc: 0.7365
Epoch 23/100
25724/25724 [==============================] - 1s 55us/sample - loss: 0.5423 - acc: 0.7342
Epoch 24/100
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5424 - acc: 0.7349
Epoch 25/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5417 - acc: 0.7345
Epoch 26/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5412 - acc: 0.7356
Epoch 27/100
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5414 - acc: 0.73640s - loss: 0.5362 -
Epoch 28/100
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5411 - acc: 0.7352
Epoch 29/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5412 - acc: 0.7345
Epoch 30/100
25724/25724 [==============================] - 2s 60us/sample - loss: 0.5405 - acc: 0.7358
Epoch 31/100
25724/25724 [==============================] - 3s 104us/sample - loss: 0.5408 - acc: 0.7357s - loss: 0.5410 - acc: 0.
Epoch 32/100
25724/25724 [==============================] - 2s 63us/sample - loss: 0.5406 - acc: 0.7359
Epoch 33/100
25724/25724 [==============================] - 2s 64us/sample - loss: 0.5403 - acc: 0.7358
Epoch 34/100
25724/25724 [==============================] - 2s 76us/sample - loss: 0.5402 - acc: 0.7347
Epoch 35/100
25724/25724 [==============================] - 2s 62us/sample - loss: 0.5400 - acc: 0.7352
Epoch 36/100
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5405 - acc: 0.7364
Epoch 37/100
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5394 - acc: 0.73780s - loss: 0.5396 - acc: 0.737
Epoch 38/100
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5395 - acc: 0.7356
Epoch 39/100
25724/25724 [==============================] - 1s 54us/sample - loss: 0.5400 - acc: 0.7381
Epoch 40/100
25724/25724 [==============================] - 2s 65us/sample - loss: 0.5389 - acc: 0.7356
Epoch 41/100
25724/25724 [==============================] - 2s 63us/sample - loss: 0.5390 - acc: 0.7362
Epoch 42/100
25724/25724 [==============================] - 2s 59us/sample - loss: 0.5397 - acc: 0.7371
Epoch 43/100
25724/25724 [==============================] - 2s 71us/sample - loss: 0.5394 - acc: 0.7359
Epoch 44/100
25724/25724 [==============================] - 2s 78us/sample - loss: 0.5387 - acc: 0.7359
Epoch 45/100
25724/25724 [==============================] - 1s 57us/sample - loss: 0.5390 - acc: 0.7357
Epoch 46/100
25724/25724 [==============================] - 1s 58us/sample - loss: 0.5391 - acc: 0.7362
Epoch 47/100
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5383 - acc: 0.7368
Epoch 48/100
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5381 - acc: 0.7370
Epoch 49/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5385 - acc: 0.7380
Epoch 50/100
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5378 - acc: 0.7377
Epoch 51/100
25724/25724 [==============================] - 1s 54us/sample - loss: 0.5374 - acc: 0.7369
Epoch 52/100
25724/25724 [==============================] - 1s 55us/sample - loss: 0.5380 - acc: 0.7373
Epoch 53/100
25724/25724 [==============================] - 1s 57us/sample - loss: 0.5382 - acc: 0.7387
Epoch 54/100
25724/25724 [==============================] - 1s 54us/sample - loss: 0.5371 - acc: 0.7381
Epoch 55/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5378 - acc: 0.7365
Epoch 56/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5378 - acc: 0.7372
Epoch 57/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5369 - acc: 0.7382
Epoch 58/100
25724/25724 [==============================] - 1s 47us/sample - loss: 0.5371 - acc: 0.7388
Epoch 59/100
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5368 - acc: 0.73780s - loss: 0.5369 - acc: 0.7
Epoch 60/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5368 - acc: 0.7379
Epoch 61/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5372 - acc: 0.7371
Epoch 62/100
25724/25724 [==============================] - 1s 47us/sample - loss: 0.5370 - acc: 0.7374
Epoch 63/100
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5366 - acc: 0.7381
Epoch 64/100
25724/25724 [==============================] - 1s 58us/sample - loss: 0.5370 - acc: 0.7383
Epoch 65/100
25724/25724 [==============================] - 1s 57us/sample - loss: 0.5372 - acc: 0.7383
Epoch 66/100
25724/25724 [==============================] - 2s 59us/sample - loss: 0.5368 - acc: 0.7376
Epoch 67/100
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5363 - acc: 0.7385
Epoch 68/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5358 - acc: 0.7371
Epoch 69/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5362 - acc: 0.7385
Epoch 70/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5360 - acc: 0.7384
Epoch 71/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5366 - acc: 0.7381
Epoch 72/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5363 - acc: 0.7381
Epoch 73/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5358 - acc: 0.7385
Epoch 74/100
25724/25724 [==============================] - 1s 53us/sample - loss: 0.5363 - acc: 0.7378
Epoch 75/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5358 - acc: 0.7392
Epoch 76/100
25724/25724 [==============================] - 2s 59us/sample - loss: 0.5362 - acc: 0.73880s - loss: 0.5352 -
Epoch 77/100
25724/25724 [==============================] - 1s 57us/sample - loss: 0.5354 - acc: 0.7395
Epoch 78/100

25724/25724 [==============================] - 1s 55us/sample - loss: 0.5399 - acc: 0.7386
Epoch 79/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5353 - acc: 0.7392
Epoch 80/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5349 - acc: 0.7390
Epoch 81/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5350 - acc: 0.7402
Epoch 82/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5355 - acc: 0.7397
Epoch 83/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5355 - acc: 0.7396
Epoch 84/100
25724/25724 [==============================] - 1s 48us/sample - loss: 0.5349 - acc: 0.7379
Epoch 85/100
25724/25724 [==============================] - 1s 47us/sample - loss: 0.5353 - acc: 0.7395
Epoch 86/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5353 - acc: 0.7376
Epoch 87/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5350 - acc: 0.73971s - loss
Epoch 88/100
25724/25724 [==============================] - 1s 56us/sample - loss: 0.5350 - acc: 0.7383
Epoch 89/100
25724/25724 [==============================] - 1s 55us/sample - loss: 0.5350 - acc: 0.7389
Epoch 90/100
25724/25724 [==============================] - 1s 54us/sample - loss: 0.5348 - acc: 0.7399
Epoch 91/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5345 - acc: 0.7386
Epoch 92/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5350 - acc: 0.7398
Epoch 93/100
25724/25724 [==============================] - 1s 54us/sample - loss: 0.5346 - acc: 0.7400
Epoch 94/100
25724/25724 [==============================] - 1s 51us/sample - loss: 0.5347 - acc: 0.7396
Epoch 95/100
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5348 - acc: 0.7393
Epoch 96/100
25724/25724 [==============================] - 1s 52us/sample - loss: 0.5343 - acc: 0.7408
Epoch 97/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5349 - acc: 0.7405
Epoch 98/100
25724/25724 [==============================] - 1s 49us/sample - loss: 0.5353 - acc: 0.7398
Epoch 99/100
25724/25724 [==============================] - 1s 50us/sample - loss: 0.5341 - acc: 0.7388
Epoch 100/100
25724/25724 [==============================] - 1s 57us/sample - loss: 0.5366 - acc: 0.7390

### Step 2: After finishing your models, display the accuracy scores achieved by each model, and compare the results.

In [49]:
print("Original Model Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Original Model Results
8575/8575 - 0s - loss: 0.5553 - acc: 0.7300
Loss: 0.5553375081070658, Accuracy: 0.7300291657447815

In [50]:
print("Alternative Model 1 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A1.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 1 Results
8575/8575 - 0s - loss: 0.5686 - acc: 0.7273
Loss: 0.5685665643806013, Accuracy: 0.7273469567298889

In [51]:
print("Alternative Model 2 Results")

# Evaluate the model loss and accuracy metrics using the evaluate method and the test data
model_loss, model_accuracy = nn_A2.evaluate(X_test_scaled,y_test,verbose=2)

# Display the model loss and accuracy results
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

Alternative Model 2 Results
8575/8575 - 0s - loss: 0.5693 - acc: 0.7305
Loss: 0.569337972291357, Accuracy: 0.7304956316947937

Alternative models did not improve as much given the amount of computational power.  I would suspect that maybe more hidden layers would help?

### Step 3: Save each of your alternative models as an HDF5 file.

In [52]:
# Export your model to a HDF5 file
nn_A1.save("AlphabetSoupA1.h5")

In [53]:
# Export your model to a HDF5 file
nn_A2.save("AlphabetSoupA2.h5")